In [1]:
import torch

a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16],
                  [17,18,19,20]])
b>10

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [2]:
device = torch.device(
    'cuda:0' if torch.cuda.is_available() else 'cpu'
)
device

device(type='cuda', index=0)

In [3]:
b = torch.rand([2,3])
b_cuda = b.to(device)
b_cuda

tensor([[0.5249, 0.0935, 0.8201],
        [0.3179, 0.6299, 0.8801]], device='cuda:0')

In [4]:
%time (b - b + b*10.0)**2

CPU times: user 1.06 ms, sys: 1.01 ms, total: 2.07 ms
Wall time: 8.98 ms


tensor([[27.5507,  0.8745, 67.2620],
        [10.1044, 39.6723, 77.4597]])

In [5]:
%time y_cuda = (b_cuda - b_cuda + b_cuda*10.0)**2

CPU times: user 11.2 ms, sys: 21.2 ms, total: 32.3 ms
Wall time: 42.9 ms


In [6]:
import matplotlib.pyplot as plt
import numpy as np
# w =  torch.tensor([[5.0, 10.0], [1.0, 2.0]], requires_grad = True)# put our code here

w =  torch.tensor([-5.0], requires_grad = True)# put our code here
w_cuda = w.to(device)

alpha = 1
print(alpha)

optimizer = torch.optim.Adam(
    [w_cuda], lr=alpha
)

function = lambda w: w.sin()+w**2/10 # put our code here


steps = np.array([[w.item(), function(w).item()]])

for _ in range(50):
    # print(w.item(), function.item(), sep="\t")

    function(w).backward()

    # w.data -= alpha * w.grad
    optimizer.step() 

    steps = np.append(steps, np.array([[w.item(), function(w).item()]]), axis=0)

    # w.grad.zero_()
    optimizer.zero_grad()

# print(steps)
x = torch.arange(-5, 5, 0.5)
y = function(x).data
# print(steps.T)
plt.plot(x, y)
print(steps.T.shape)
print(steps.T[:,0])

for i in range(steps.shape[0]):
    # print(*steps.T[:, i])
    plt.plot([steps.T[:,i][0]], [steps.T[:,i][1]])
# plt.show()

1


ValueError: can't optimize a non-leaf Tensor