In [2]:
import torch

In [3]:
a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16],
                  [17,18,19,20]])
b>10

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [4]:
device = torch.device(
    'cuda:0' if torch.cuda.is_available() else 'cpu'
)
device

device(type='cuda', index=0)

## Conv2d - Свертка

Класс нейронной сети: `torch.nn.Conv2d`
Функция: `torch.nn.functional.conv2d`

In [45]:
input = torch.randint(-5, 5, (1, 5, 5), dtype=torch.float32)
filter = torch.Tensor([[
    [[1,1,1],
     [1,1,1],
     [1,1,1]]
]])
print(input)
print(filter)
print(torch.nn.functional.conv2d(input, filter, padding=1))

tensor([[[-3., -2.,  3.,  4., -4.],
         [ 3.,  2., -5.,  2., -1.],
         [-4.,  3., -3., -2.,  0.],
         [ 1., -5.,  4.,  4., -2.],
         [-5., -2.,  0., -1.,  3.]]])
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
tensor([[[  0.,  -2.,   4.,  -1.,   1.],
         [ -1.,  -6.,   2.,  -6.,  -1.],
         [  0.,  -4.,   0.,  -3.,   1.],
         [-12., -11.,  -2.,   3.,   2.],
         [-11.,  -7.,   0.,   8.,   4.]]])


In [69]:
m = torch.nn.Conv2d(in_channels=1, out_channels=2, kernel_size=3, padding=1)
input = torch.randint(-5, 5, (1, 5, 5), dtype=torch.float32)
print(input)
output = m(input)
print(output)
print(m.weight)



tensor([[[ 1.,  3., -2., -2., -1.],
         [ 2.,  0., -5.,  1.,  0.],
         [-5.,  0.,  3.,  0.,  0.],
         [-2., -3.,  4., -3.,  3.],
         [ 3., -5., -1.,  2., -3.]]])
tensor([[[ 0.3671,  0.4137,  0.4076,  0.2607, -0.2481],
         [ 0.5437,  0.3850, -0.2144, -0.8811,  0.0215],
         [ 0.7344,  0.7319, -0.0646, -0.2758,  0.2093],
         [-0.6407,  0.2162,  0.4130,  1.1761,  0.0219],
         [-0.4278, -0.7765,  0.5682, -0.8547,  0.3994]],

        [[ 0.0397, -1.4016,  0.1273,  0.5925, -1.1801],
         [ 0.2219,  2.6528, -0.5265, -3.1649, -0.6485],
         [-1.2103, -0.1044, -0.1049, -1.3223,  1.0141],
         [-2.2830, -3.0945,  1.7448,  0.9328, -1.3957],
         [-0.7628, -0.6796, -1.8656,  0.3438, -0.3548]]],
       grad_fn=<SqueezeBackward1>)
Parameter containing:
tensor([[[[ 0.0300,  0.1108, -0.1001],
          [ 0.0883,  0.0412,  0.1468],
          [-0.1344, -0.1093, -0.1320]]],


        [[[ 0.2269,  0.1563,  0.1043],
          [ 0.2377,  0.1140,  0.0407]

## BatchNorm2D - Z-нормализация значений
$$
\hat{X}_{ij}=\dfrac{X_{ij}-M(X)}{\sqrt{D(X)}}
$$

In [66]:
# # With Learnable Parameters
# m = nn.BatchNorm2d(100)
# Without Learnable Parameters
m = torch.nn.BatchNorm2d(1, affine=False)
input = torch.randn(1, 1, 5, 5)
output = m(input)
print(input)
print(output)

tensor([[[[-0.2208,  1.3094, -0.8979,  0.7133,  0.9332],
          [ 1.9611,  0.3690,  0.3885, -0.4287, -0.8214],
          [-0.0661,  0.1791, -0.3184,  0.8698, -0.8706],
          [-0.1126, -0.8478,  0.3033,  1.7663,  0.0358],
          [ 1.8082,  0.9555, -0.6013, -0.7609, -1.1584]]]])
tensor([[[[-4.4534e-01,  1.2570e+00, -1.1987e+00,  5.9389e-01,  8.3856e-01],
          [ 1.9822e+00,  2.1077e-01,  2.3257e-01, -6.7665e-01, -1.1135e+00],
          [-2.7327e-01, -4.0798e-04, -5.5391e-01,  7.6798e-01, -1.1683e+00],
          [-3.2500e-01, -1.1429e+00,  1.3767e-01,  1.7654e+00, -1.5984e-01],
          [ 1.8120e+00,  8.6333e-01, -8.6873e-01, -1.0462e+00, -1.4885e+00]]]])


## nn.ReLU() - Функция активации
$$
\text{ReLU}(x)=(x)^{+}=\max(0,x)
$$

In [68]:
m = torch.nn.ReLU()
input = torch.randn(1, 5,5)
print(input)
output = m(input)
print(output)

tensor([[[ 0.5306, -1.0873,  0.3781,  0.7720,  0.0051],
         [-0.4473,  0.5501,  0.2220,  0.8677, -0.8221],
         [ 3.1223,  0.2004, -0.8885, -0.4503,  0.5934],
         [-0.5009,  0.2388, -0.4687, -0.4619, -0.8139],
         [-0.7756, -3.1576,  0.2554,  0.0196,  1.0696]]])
tensor([[[0.5306, 0.0000, 0.3781, 0.7720, 0.0051],
         [0.0000, 0.5501, 0.2220, 0.8677, 0.0000],
         [3.1223, 0.2004, 0.0000, 0.0000, 0.5934],
         [0.0000, 0.2388, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.2554, 0.0196, 1.0696]]])


## nn.Droupout(p)
В тензоре с вероятностью $p$ зануляет ячейки

In [ ]:
m = torch.nn.Dropout(p=0.7)
input = torch.randn(5, 5)
print(input)
output = m(input)
print(output)

tensor([[ 0.0947,  0.0577,  0.6171,  0.6495,  1.3487],
        [ 0.7029, -0.5120, -0.1837,  0.3355, -0.1357],
        [ 0.4206,  0.1237,  0.4283,  0.5280,  0.2379],
        [-0.4296,  1.2909,  0.5506, -0.4133,  1.0075],
        [ 0.6925,  0.5797, -0.3572,  0.1872,  0.2814]])
tensor([[ 0.0000,  0.0000,  2.0569,  2.1650,  0.0000],
        [ 0.0000, -0.0000, -0.6122,  1.1184, -0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-1.4321,  0.0000,  0.0000, -0.0000,  0.0000],
        [ 0.0000,  1.9324, -0.0000,  0.0000,  0.9381]])


## nn.Linear() - Слой линейных нейронов
$$
N(X)=\sum_{n}{w_{n}\cdot x_n}
$$

In [81]:
m = torch.nn.Linear(5, 1)
input = torch.randn(4, 5)
print(input)
print(m.weight)
output = m(input)
print(output)

tensor([[-0.0243, -0.3554,  0.8004, -0.2180,  0.0337],
        [-2.8384,  0.7254,  0.0088,  0.0549, -0.1272],
        [-1.0088, -0.7088, -0.8595,  2.6259,  1.1794],
        [-1.6444,  0.2261,  0.1165,  0.7941,  0.2773]])
Parameter containing:
tensor([[-0.3035, -0.3829, -0.3719,  0.0549,  0.1667]], requires_grad=True)
tensor([[-0.1743],
        [ 0.5485],
        [ 1.2241],
        [ 0.4452]], grad_fn=<AddmmBackward0>)


In [78]:
(input*m.weight).sum()

tensor(-1.0321, grad_fn=<SumBackward0>)

## torch.Tensor.view(shape) - Изменить форму тензора

In [89]:
x = torch.randint(-5,5,(4,4))
print(x)

print(x.view(2,8))
print(x.view(8,-1))

tensor([[ 2, -5, -5,  4],
        [-2, -3,  2, -4],
        [-5,  4,  3,  0],
        [-5, -5,  0,  3]])
tensor([[ 2, -5, -5,  4, -2, -3,  2, -4],
        [-5,  4,  3,  0, -5, -5,  0,  3]])
tensor([[ 2, -5],
        [-5,  4],
        [-2, -3],
        [ 2, -4],
        [-5,  4],
        [ 3,  0],
        [-5, -5],
        [ 0,  3]])


## torch.backends.cudnn.deterministic = True - Настройка определенности вычисленных результатов

При Истине, результат при одинаковых входах должен выдавать определенный один результат

# Список доступных функций модели
## Критерий оценки модели при обучении
- `nn.L1Loss()` - $\|x_n-y_n\|$
- `nn.MSELoss()` - $(x_n-y_n)^2$
- `nn.CrossEntropyLoss()` - $\frac{e^{x_{n,y_n}}}{\sum_{c=1}^{C}{e^{x_{n,c}}}}$
- `nn.BCELoss()` - 